package org.sopt.kareer.domain.member.entity.constants;

import java.util.List;

public class Field {

    private Field() {
    }

    public static final List<String> FIELD_LIST = List.of(
            "Automotive",
            "Aerospace",
            "Energy",
            "Oil & Gas",
            "Renewable Energy",
            "Manufacturing",
            "Construction",
            "Engineering",
            "Healthcare",
            "Pharmaceuticals",
            "Biotechnology",
            "Medical Devices",
            "Education",
            "EdTech",
            "Finance",
            "Banking",
            "Insurance",
            "FinTech",
            "Investment & Asset Management",
            "Retail",
            "E-commerce",
            "Consumer Goods",
            "Telecommunications",
            "Media",
            "Entertainment",
            "Gaming",
            "Agriculture",
            "Food & Beverage",
            "Hospitality",
            "Travel & Tourism",
            "Logistics",
            "Supply Chain",
            "Real Estate",
            "Consulting",
            "Legal",
            "Government & Public Sector",
            "Nonprofit & NGO",
            "Information Technology",
            "Software Development",
            "Artificial Intelligence",
            "Data & Analytics",
            "Cybersecurity",
            "Cloud Computing",
            "Blockchain",
            "Internet of Things (IoT)",
            "Robotics",
            "Semiconductors",
            "Electronics",
            "Hardware",
            "Design",
            "Marketing & Advertising",
            "Human Resources",
            "Sports",
            "Fashion & Apparel",
            "Beauty & Cosmetics",
            "Environment",
            "Sustainability",
            "Smart City",
            "Defense",
            "Space Industry"
    );
}
