package org.sopt.kareer.domain.member.entity.constants;

import java.util.List;

public class University {

    private University() {
    }

    public static final List<String> UNIVERSITY_LIST = List.of(
            "Kunsan National University",
            "Kongju National University",
            "Gyeongguk National University",
            "Gangneung Wonju National University",
            "Kwangju Women’S University",
            "Gwangju University",
            "Gwangju National University Of Education",
            "Gwangju Institute Of Science And Technology",
            "Gwangju Catholic University",
            "Kwangwoon University",
            "Kwangshin University",
            "Gongju National University Of Education",
            "Kosin University",
            "The Cyber University Of Korea",
            "Korea University Sejong Campus",
            "Korea University",
            "Keimyung University",
            "Kyung Hee Cyber University",
            "Kyung Hee University",
            "Kyungil University",
            "Gyeongin National University Of Education",
            "Kyungwoon University",
            "Kyungsung University",
            "Gyeongsang National University",
            "Kyungpook National University",
            "Kyungdong University",
            "Kyungnam University",
            "Gyeongnam National University Of Science And Technology",
            "Kyonggi University",
            "Konyang Cyber University",
            "Konyang University",
            "Konkuk University",
            "Kangwon National University",
            "GANGSEO UNIVERSITY",
            "Kangnam University",
            "Methodist Theological University",
            "The Catholic University Of Korea",
            "Catholic Kkottongnae University",
            "Catholic Kwandong University",
            "Gachon University",
            "Kaya University",
            "Gyeonggi University Of Science And Technology",
            "Geoje University",
            "Gangwon State University",
            "Kangwon Tourism College",
            "Gangneung Yeongdong University",
            "Gangdong University",
            "Catholic Sangji College",
            "ICT Polytech Institute of Korea",
            "Hwashin Cyber University",
            "HWASUNG MEDI-SCIENCE UNIVERSITY",
            "Hongik University",
            "Howon University",
            "Hoseo University",
            "Honam Theological University & Seminary",
            "Honam University",
            "Hyupsung University",
            "Hanzhong University",
            "Haniluniv.&Presb.Theol.Sem.",
            "Hanyang Cyber University",
            "Hanyang University Erica Campus",
            "Hanyang University",
            "Hanshin University",
            "Hansei University",
            "Hansung University",
            "Hanseo University",
            "Hanbuk University",
            "Hanbat National University",
            "Hallym University",
            "Hanlyo University",
            "Halla University",
            "Handong Global University",
            "Hannam University",
            "Korea Aerospace University",
            "Korea Baptist Theological University/Seminary",
            "Korea National Sport University",
            "Korea National University Of Cultural Heritage",
            "Hankuk University Of Foreign Studies",
            "Korea National University Of Arts",
            "Open Cyber University Of Korea (OCU)",
            "Korea institute of Energy Technology",
            "Korean Bible University",
            "Korea National Open University",
            "Korea University of Technology and Education",
            "Korea National University Of Education",
            "Korea Advanced Institute of Science And Technology(KAIST)",
            "Tech University of Korea",
            "Hankyong National University",
            "Pohang University Of Science And Technology (Postech)",
            "Pyeongtaek University",
            "TAEJAE UNIVERSITY",
            "Tamna University",
            "Calvin University",
            "Chungbuk National University",
            "Chungnam National University",
            "Chuncheon National University Of Education",
            "Chugye University For The Arts",
            "Chongshin University",
            "Chodang University",
            "Cheongju University",
            "Chongjunationaluniversityofeducation",
            "Chungwoon University",
            "Changshin University",
            "CHA University",
            "Jinju National University",
            "Chinju National University Of Education",
            "Jungwon University",
            "Joong-Ang Sangha University",
            "Chung-Ang University",
            "Joongbu University",
            "Chosun University",
            "Jeju National University",
            "Jeju International University",
            "Jungseok Institute Of Technology",
            "Jeonju University",
            "Jeonju National University Of Education",
            "Jeonbuk National University",
            "Chonnam National University",
            "Presbyterian University & Theological Seminary",
            "Inha University",
            "Incheon National University",
            "Incheon Catholic University",
            "Inje University",
            "Ewha Womans University",
            "Eulji University",
            "U1 University",
            "Uiduk University",
            "Wonkwang Digital University",
            "Wonkwang University",
            "University Of Ulsan",
            "Ulsan National Institute of Science and Technology",
            "Woosong University",
            "Woosuk University",
            "Yong In University",
            "Yewon Arts University",
            "Jesus University",
            "Youngsan University Of Seon Studies",
            "Youngsan University",
            "Youngnam Theological University & Seminary",
            "Yeungnam University",
            "Yonsei University MIRAE Campus",
            "Yonsei University",
            "Anyang University",
            "Ajou University",
            "ACTS University",
            "Shinhan University",
            "Silla University",
            "SinGyeongju University",
            "Korea Soongsil Cyber University",
            "Soongsil University",
            "Soonchunhyang University",
            "Korea Christian College",
            "Sookmyung Women’S University",
            "The University Of Suwon",
            "Suwon Catholic University",
            "Songwon University",
            "Sehan University",
            "Sejong Cyber University",
            "Sejong University",
            "Semyung University",
            "Sungshin Women’S University",
            "Sungkyunkwan University",
            "Sungkonghoe University",
            "Sungkyul University",
            "Sun Moon University",
            "Seowon University",
            "Seoul Hanyoung University",
            "Seoul Jangsin University",
            "Seoul Women’s University",
            "Seoul Theological University",
            "University Of Seoul",
            "Seoul Cyber University",
            "Seoul Digital University",
            "Seoul National University",
            "Seoul Christian University",
            "Seoul National University Of Education",
            "Seoul National University Of Science And Technology",
            "Seonam University",
            "Seokyeong University",
            "Sogang University",
            "Sangji University",
            "Sangmyung University",
            "Sangmyung University (Seoul)",
            "Sahmyook University",
            "Cyber Hankuk University Of Foreign Studies",
            "Busan Presbyterian University",
            "Busan University Of Foreign Studies",
            "Busandigital University",
            "Pusan National University",
            "Busan National University Of Education",
            "Catholic University Of Pusan",
            "Baekseok University",
            "Pai Chai University",
            "Mokpo Catholic University",
            "Mokwon University",
            "Myongji University Social Science Campus",
            "Myongji University Natural Science Campus",
            "Luther University",
            "Digital Seoul Culture Arts University",
            "Dong-Eui University",
            "Dongyang University",
            "Dong-A University",
            "Dongshin University",
            "Dongseo University",
            "Tongmyong University",
            "Dongduk Women’s University",
            "Dongguk University",
            "Duksung Women’S University",
            "Daejin University",
            "Daejeon Theological University",
            "Daejeon University",
            "Daejeoncatholic University",
            "Daeshin University",
            "Daegu Haany University",
            "Daegu University Of Foreign Studies",
            "Daegu Arts University",
            "Daegu Cyber University",
            "Daegu University",
            "Daegu National University Of Education",
            "DGIST",
            "Daegu Catholic University",
            "Dankook University",
            "Namseoul University",
            "Nambu University",
            "Korea Nazarene University",
            "Gimcheon University",
            "Geumgang University",
            "Global Cyber University",
            "Far East University",
            "Gukje Cyber University",
            "Kookmin University",
            "Korea Maritime & Ocean University",
            "Korea National University Of Transportation",
            "Changwon National University",
            "Sunchon National University",
            "Pukyong National University",
            "Mokpo National Maritime University",
            "Mokpo National University",
            "Kumoh National Institute Of Technology"
    );
}
