global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kareer_server'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: [ 'api.ka-reer.com:443' ]  # HTTPS를 통해 접근
        labels:
          application: kareer_server