auth_enabled: false  # 인증 사용없이 Promtail이 바로 로그 보낼 수 있음

server:
  http_listen_port: 3100  # Loki가 HTTP로 요청 받을 포트 (Promtail, Grafana에서 접근)

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks  # 로그 청크 데이터 저장 위치. Loki는 로그를 청크 단위로 저장

schema_config:  # Loki 내부 스키마 설정
  configs:
    - from: 2026-03-20
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h  # 하루 단위로 인덱스 파일 생성